### ISSUE TITLE
PersistentSubscriptionSettingsBuilder requires all settings in constructor

### ISSUE THREAD

**Issue by SlayerBirden** [prooph/event-store-client#101]
It seems not logical to have `PersistentSubscriptionSettingsBuilder` require the same settings that `PersistentSubscriptionSettings` does - what's the benefit of using builder with all the setters inside...
I think it should have the same structure as `ConnectionSettingsBuilder` with defaults set to variables and no constructor args.

If that makes sense I can create a PR for it, thanks.

**Comment by prolic** [comment]
Good catch, it seems like I totally missed that!

Here are the defaults:

```
bool resolveLinkTos, long startFrom, bool timingStatistics,
			TimeSpan timeout,
			int bufferSize, int liveBufferSize, int maxRetryCount, int readBatchSize,
			TimeSpan checkPointAfter, int minCheckPointCount,
			int maxCheckPointCount, int maxSubscriberCount, string namedConsumerStrategies
```

=>

```
false,
				-1,
				false,
				TimeSpan.FromSeconds(30),
				500,
				500,
				10,
				20,
				TimeSpan.FromSeconds(2),
				10,
				1000,
				0,
				SystemConsumerStrategies.RoundRobin);
```
