### ISSUE TITLE
Default UserCredentials

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-client#102]
Since commit https://github.com/prooph/event-store-client/commit/0d4d18d20a1ca90506b5c825e04079e05a73a624 all the `*Manager` classes support passing default UserCredentials. The main API for async communication (`Prooph\EventStoreClient\Internal\EventStoreNodeConnection`) however does not. 

Your old [comment](https://github.com/prooph/event-store-client/issues/55#issuecomment-444886854) in #55 suggests that this might have been supported before though - I'm not sure...

Anyway I'd like open some discussion and sort this out. I can send a PR but I'm not sure whether the default credentials are wanted and if so then whether they should be added as another argument to `EventStoreNodeConnection::__construct()` or rather into `Prooph\EventStoreClient\ConnectionSettings`.

**Comment by enumag** [comment]
ping @prolic

**Comment by prolic** [comment]
see here: https://github.com/prooph/event-store-client/blob/master/src/Internal/EventStoreConnectionLogicHandler.php#L449

Using http connection you need to authenticate every single request. Using the tcp connection, you only authenticate the connection once, and after that you can set credentials to override only.

**Comment by enumag** [comment]
Oh, somehow I didn't notice. Thank you!
