### ISSUE TITLE
Support EventStore v6

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-client#114]
support gRPC client as well?

**Comment by rodion-k** [comment]
TCP interface deprecated in Event Store 6.0.0 Preview 3

**Comment by enumag** [comment]
The problem is that ext-grpc doesn't support non-blocking API. See https://github.com/grpc/grpc/issues/12017.

**Comment by prolic** [comment]
I am running this library with `EventStoreDB 20.10.0 (LTS)` in production, GRPC is an issue, but for now everything works.
