### ISSUE TITLE
Support UUID1 / UUID5, ...

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-client#119]

**Comment by BoyeMagnus** [comment]
Would it be possible to support just an interface instead of a class? That way people can provide their own implementations?

**Comment by prolic** [comment]
Maybe, but I need to make sure it's a valid GUID, otherwise you'll run into problems. Using `Ramsey` in PHP, you need to enable the `GuidStringCodec` in the `FeatureSet`. That's why I thought initially that a class that doesn't allow you the freedom to break the event store is the better solution.
I need to have a look, because I thin different types of UUID's are a valid feature requirement.

**Comment by prolic** [comment]
Am I stupid?

https://github.com/ramsey/uuid/issues/306
