### ISSUE TITLE
RC not compatible with any release of "prooph/event-sourcing"

### ISSUE THREAD

**Issue by patrickkusebauch** [prooph/event-store-client#123]
The proposed RC depends on "dev-master" of "prooph/event-store". However the latest release of "prooph/event-souring" (even dev-master) require "prooph/event-store" as "^7.0". Therefore it is not possible to install both at the same time. I had to resort to installing "1.0.0-beta-8" that does not have an unrestricted dependency.

**Comment by prolic** [comment]
Do not, I repeat, do NOT use prooph/event-sourcing with this library. Refer to the [event-sourcing blueprints](https://github.com/prooph/documentation/blob/master/event-store-client/blueprints.md) instead.
