### ISSUE TITLE
Add psalm

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-client#127]
This can also make some interfaces obsolete, like `EventAppearedOnSubscription` and `SubscriptionDropped`, because we can have psalm check for correct callables. There's a downside as this is "only" checked with a static analysis tool and not at runtime directly, on the other we can remove quite some code and for end-users it's was more comfortable to just pass a callable, compared to writing a new class and implementing some interface.

see:
https://github.com/prooph/event-store-client/blob/master/src/Internal/EventStoreNodeConnection.php#L642-L643

and:
https://github.com/prooph/event-store-client/blob/master/examples/demo-subscribe-to-stream.php#L49-L72

Note: This has to be done in event-store main repository as well.

**Comment by enumag** [comment]
👍  Yeah, I agree... having interfaces for callbacks is cool but also complicates the usage since you have to write an anonymous class, constructor, property etc. to use some service in the event. Would also make the last missing piece of #117 much cleaner.
