### ISSUE TITLE
[RFC] Adding PHPdoc to generate API docs

### ISSUE THREAD

**Issue by Nek-** [prooph/event-store-client#128]
Do you think it's a bad idea?

**Comment by Nek-** [comment]
Closing because there is already some phpdoc (not enough to make a good doc though) and also there's some hidden documentation here: https://github.com/prooph/documentation/blob/master/event-store-client/index.md

**Comment by prolic** [comment]
Yeah, documentation will go online together with final release. The documentation needs some bits here and there still, but right now most work goes into polishing the library.
