### ISSUE TITLE
[RFC] Removing "type" from projections management

### ISSUE THREAD

**Issue by Nek-** [prooph/event-store-client#136]
I'm not sure on that one but it looks like they removed the `type` argument on methods related to the projections.

I assume the type cannot be something else than JS?

Method `createContinuousAsync` as an example here:
https://github.com/EventStore/EventStore/blob/a8d5029968ddde7972c3d0be4cf1ef693359ccc5/src/EventStore.ClientAPI/Projections/ProjectionsManager.cs#L99

**Comment by prolic** [comment]
As for this client, no, but if we want to add postgres support for v8, the type would be "PHP".
