### ISSUE TITLE
Change constructors for http communications

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-client#141]
Current we use this:

`string $httpSchema = EndpointExtensions::HTTP_SCHEMA,`

change to:

`bool $tlsTerminatedEndpoint`

and then

`$httpSchema = $tlsTerminatedEndpoint ? EndpointExtensions.HTTPS_SCHEMA : EndpointExtensions.HTTP_SCHEMA;`

**Comment by prolic** [comment]
QueryManager, ProjectionManager, UserManager, f.e.

**Comment by prolic** [comment]
@unixslayer interessted?

**Comment by unixslayer** [comment]
@prolic always ;)
