### ISSUE TITLE
EventStorePersistentSubscription is in namespace internal but required to be used

### ISSUE THREAD

**Issue by Nek-** [prooph/event-store-client#144]
When you connect to a pesistent subscription to handle error you need to typehint from internal.
```php
yield $this->connection->connectToPersistentSubscriptionAsync(
    $subscriptionName,
    'postgre-read-model',
    \Closure::fromCallable($this->eventAppeared),
    function (EventStorePersistentSubscription $eventStorePersistentSubscription, SubscriptionDropReason $subscriptionDropReason, \Throwable $e) {
        dump($e);
    }
);
```

This class is not marked as internal and we do not need to instantiate it, so there's no impact on IDE and feels not that bad. This is just weird, so I report it.

**Comment by prolic** [comment]
This class is in internal namespace, but the `@internal` annotation has been removed.
