### ISSUE TITLE
MemberInfoDto timeStamp is a string, not int as the code suggests for a v5 cluster

### ISSUE THREAD

**Issue by grymmare** [prooph/event-store-client#150]
I'm connecting to a v5 cluster using DNS resolution and the latest dev-master

`Typed property Prooph\EventStoreClient\Messages\ClusterMessages\MemberInfoDto::$timeStamp must be int, string used`

The data received for `timeStamp` is indeed a `string` 

```
string(9) "timeStamp"
string(27) "2020-11-26T08:12:07.451473Z"

```
Not sure if v20.6 returns an integer or a timestamp, I have not been able to test. 

I resolved this on my end by patching with composer autoload config and changing the type to string. Also didn't find any usages of MemberInfoDto::timeStamp()

**Comment by prolic** [comment]
I have to double check about this type information, hopefully will get to it this weekend. I think this value is never used anyway, and only interesting in debugging scenarios.

**Comment by enumag** [comment]
https://github.com/prooph/event-store-client/commit/70281782c87b8976c859476bcf07b40566096129
