### ISSUE TITLE
Event Store is now secure by default

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-client#153]
https://github.com/prooph/event-store-client/commit/a7b6c3132e6abeb90cbb58fb9dee2df668fdf085

This commit causes https://github.com/prooph/event-store-client/blob/master/src/ConnectionSettings.php#L120.

1. I'm now required to call `useSslConnection()` but it requires "targetHost" and I'm not sure what exactly I should pass there. I specified where to connect using the `EndPoint` object passed to `EventStoreConnectionFactory::createFromEndPoint()`. Should this host be the same? Documentation says "The hostname expected on the certificate" - what certificate?
2. There is no method in the builder to override the new default and disable ssl.

**Comment by prolic** [comment]
my bad, fixed via  0b3d028

**Comment by enumag** [comment]
cool but I'd still like to know how to use ssl 🤔

**Comment by prolic** [comment]
I can show you my setup:

For single-node connection (staging, development mode) use this connection string:

`ConnectTo=tcp://admin:changeit@eventstore:1113`

For 3-node-cluster and secure connection (production) use this connection string:

`ConnectTo=discover://admin:changeit@eventstore:2113;useSslConnection=true;targethost=eventstore`

(you'd have another host name here usually)

Next I have a class like this:

```
final class EventStoreConfig
{
    private string $connectionString;
    private string $httpEndPoint;
    private int $httpPort;
    private bool $tlsTerminatedEndpoint;
    private bool $verifyPeer;
    private string $username;
    private string $password;
    
    ...
}
```

Now create event store connection:

```
    function buildEventStoreConnection(EventStoreConfig $config, LoggerInterface $logger): EventStoreConnection
    {
        $settings = ConnectionSettings::create()
            ->setDefaultUserCredentials(
                new UserCredentials($config->username(), $config->password())
            )
            ->useCustomLogger($logger);

        if ($config->tlsTerminatedEndpoint()) {
            $settings = $settings->useSslConnection($config->httpEndPoint(), $config->verifyPeer());
        }

        return EventStoreConnectionFactory::createFromConnectionString(
            $config->connectionString(),
            $settings->build()
        );
```

**Comment by enumag** [comment]
Can you share your `$config->connectionString()` method? 🤔

**Comment by prolic** [comment]
This is a simple getter. I provided the connection string before, one for
dev/staging via single node, the other for production via DNS cluster
discovery.
