### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-client#156]
My project has been suffering from occasional segmentation faults on exit for a while. Recently we finally managed to reproduce the issue with debug PHP and the stacktrace hinted that it's not a PHP issue but ext-protobuf issue so I reported it here: https://github.com/protocolbuffers/protobuf/issues/8454

Based on their feedback the problem is that we create a protobuf message in a `__destruct` method:
https://github.com/prooph/event-store-client/blob/46e4a7d1972a18d0f590e61361c007abd38cd42d/src/Internal/EventStoreNodeConnection.php#L924-L927
https://github.com/prooph/event-store-client/blob/46e4a7d1972a18d0f590e61361c007abd38cd42d/src/Internal/EventStoreNodeConnection.php#L115-L118

What is the reason for doing this?

**Comment by enumag** [comment]
Same problem is here as well:

https://github.com/prooph/event-store/blob/00a54a3860c8598453f1e365c4e34ef789a40043/src/EventStoreSubscription.php#L51-L54

**Comment by prolic** [comment]
Thanks for reporting. I'm going to look into this, but currently I'm sick, so it may take a few days.

**Comment by enumag** [comment]
ping @prolic
