### ISSUE TITLE
Reconnecting for subscriptions in a cluster fails

### ISSUE THREAD

**Issue by pkruithof** [prooph/event-store-client#37]
When using service discovery, connecting to a persistent subscription fails. I'll try to explain what happens:

1. Discovery starts, ES responds with the 'best choice', which is usually a slave node
2. The `ConnectToPersistentSubscription` call is made
3. ES responds with a `NotHandled - NotMaster` package
4. The client disconnects
5. The client tries to remove the active subscription, but since no active subscription was made, that fails.
6. Client is killed (though I think this is done by Kubernetes in our case)

The entire log is here: 
https://gist.github.com/pkruithof/e62baf50f3b1e1334b4929100fdf70e7

**Comment by prolic** [comment]
That's not that easy so solve, so I created an issue here first: https://github.com/EventStore/ClientAPI.NetCore/issues/42

**Comment by prolic** [comment]
@pkruithof As this is an issue within the original Client (and maybe even in the server implementation) I'll close this issue. You can track the created issue on their repository, and once they resolve it somehow, I can do something about it here as well.

For now: Just create a subscription first, as this will reconnect for you. You'll receive an `ExistsAlready` response and that's it.

**Comment by pkruithof** [comment]
Creating is part of our deployment process, but we do an update call first, which has the same effect. Thanks for thinking along 👍
