### ISSUE TITLE
Imposibility to edit native projections

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-client#56]
Currently it's impossible to use `SyncProjectionsManager` / `AsyncProjectionsManager` to update the query of a native projection such as `$by_category` because `ProjectionsClient::updateQuery()` always [adds](https://github.com/prooph/event-store-client/blob/8abe84c6c235883ba3017bf6e7bb6514f58b2499/src/Projections/ProjectionsClient.php#L471) `&type=JS` which breaks the native projection.

I would send a PR but I'm unsure how do you want to solve this so let's discuss first.

**Comment by enumag** [comment]
It is possible and it is even [documented](https://eventstore.org/docs/projections/system-projections/index.html#by-category):

> This projection links existing events from streams to a new stream with a $ce- prefix (a category) by splitting a stream id by a **configurable separator**.

That's what I'm changing, the default separator is `-` and I'm changing it to `.`.

**Comment by enumag** [comment]
And no the query is not written in JS. As documented it's simply two lines of text:

default:

```
first
-
```

my:

```
first
.
```

**Comment by enumag** [comment]
I understand that your opinion is that it's better practice to not change the native projections. But I still think it should be possible.

See https://github.com/EventStore/EventStore/issues/1451 and https://github.com/EventStore/EventStore/pull/1472

**Comment by prolic** [comment]
Thanks for your input, as it's resolved now I will close this ticket.

**Comment by enumag** [comment]
Ah, you reverted the revert. Ok. :-D
