### ISSUE TITLE
Bug in tests using lib-uv

### ISSUE THREAD

**Issue by prolic** [prooph/event-store-client#75]

**Comment by enumag** [comment]
Is this still happening? Should I rather use some other extension than uv until this is resolved? Which Amphp loop implementation are you using in your projects and why?

**Comment by prolic** [comment]
Usually you don't need any event-loop extension at all. There is only a performance difference when you have high numbers of concurrent socket connections.

The issue is still relevant (using uv here):

```
./vendor/bin/phpunit --exclude-group=ignore --stop-on-failure                        
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

...............................................................  63 / 482 ( 13%)
............................................................... 126 / 482 ( 26%)
............................................................... 189 / 482 ( 39%)
.............................................................php: src/unix/core.c:888: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
[1]    9105 abort      ./vendor/bin/phpunit --exclude-group=ignore --stop-on-failure
./vendor/bin/phpunit --exclude-group=ignore --stop-on-failure  8.05s user 1.16s system 18% cpu 50.089 total
```

I think this is a bug in the event-store-client implementation, but unfortunately I wasn't have to isolate the problem and fix it (yet).

**Comment by prolic** [comment]
@kelunik @trowski any ideas on how to debug this?

**Comment by kelunik** [comment]
Please report this to the amphp / amp repository.

**Comment by prolic** [comment]
@kelunik already done here: https://github.com/amphp/amp/issues/292

unfortunately without response so far.

**Comment by kelunik** [comment]
Oops, sorry, should have been bwoebi/php-uv...

**Comment by prolic** [comment]
Root cause is finally found! I'm working on resolving this issue, but I have to change a couple hundred of tests, so will take a little.
