### ISSUE TITLE
v1.0.0-beta-9 requires prooph/event-store dev-master instead of v8.0.0-beta-1

### ISSUE THREAD

**Issue by SunMar** [prooph/event-store-client#82]
Hi,

Just tried to update to `v1.0.0-beta-9` but composer started complaining because it depends on `"prooph/event-store": "dev-master"` instead of `v8.0.0-beta-1`. This is more of a FYI. I solved it by adding in the `composer.json` of my root project:
```
"prooph/event-store": "v8.0.0-BETA-1 as dev-master",
```

**Comment by prolic** [comment]
thanks for the hint, I hope for next beta I think about this :)
