### ISSUE TITLE
Reconnect to persistent subscription after a connection drop

### ISSUE THREAD

**Issue by jvdlaar** [prooph/event-store-client#85]
I was testing if my client reconnects to a persistent subscription when it looses it's connection. So I see the Subscription dropped callback being called and I also see the onReconnecting and onConnected callbacks being called. But after it reconnects it won't automatically listen to the persistent subscription. Therefore I moved my entire "connect to the subscription" logic into the onConnected callback.

This seems to work for heartbeat lost reconnects. But not when I restart my eventstore. Then it seems to do the reconnect just fine. But it waits indefinitely for the createPersistentSubscriptionAsync promise. If I look into the server communication then i see this:

Client:
```
15:01:06 INFO      [app] Connected to the eventstore
15:01:06 DEBUG     [app] EventStoreNodeConnection 'listing:appearance:consume:000000005a8c43e80000000023a2feb3': enqueing message StartOperationMessage
15:01:06 DEBUG     [app] EventStoreNodeConnection 'listing:appearance:consume:000000005a8c43e80000000023a2feb3': StartOperation schedule CreatePersistentSubscription, Stream: ListingFeedItemAppearanceMarkerV1, Group Name: Main, 10, 7000
15:01:06 DEBUG     [app] EventStoreNodeConnection 'listing:appearance:consume:000000005a8c43e80000000023a2feb3': ExecuteOperation package CreatePersistentSubscription, e577b257e8f6674785975c89a8919dbc, Operation CreatePersistentSubscription (e577b257e8f6674785975c89a8919dbc): Stream: ListingFeedItemAppearanceMarkerV1, Group Name: Main, retry count: 0, created: 2019-02-05T15:01:06.905455+00:00, last updated: 2019-02-05T15:01:06.905498+00:00
```

Server:
```
event-store      | [00001,09,15:01:06.902] Connection 'external-normal' ({4ef3b3bf-c53a-4de1-9242-4d52bf06b934}) identified by client. Client connection name: 'listing:appearance:consume:000000005a8c43e80000000023a2feb3', Client version: V2.
```

When I add a sleep before creating the subscription then it seems to work. So it feels like the eventstore just ignores the create request because it's not booted completely yet. I would think that the operation timeout would kick in and throw errors or something.

My code:
```php
        Loop::run(function (): Generator {
            $this->logger->info(
                sprintf('Starting consumer for "%s"', $this->subscription)
            );
 
            yield $this->connection->connectAsync();
 
            $this->connection->onReconnecting(function () {
                $this->logger->info('Reconnecting to the eventstore');
            });
            $this->connection->onConnected(function () {
                $this->logger->info('Connected to the eventstore');
 
                // Workaround to connect to the right node in a cluster.
                $promise = $this->connection->createPersistentSubscriptionAsync(
                    $this->subscription->getStream(),
                    $this->subscription->getGroupName(),
                    $this->subscription->getSettings()
                );
 
                $promise->onResolve(function () {
                    $eventAppeared = $this->createEventAppearedHandler();
 
                    $promise = $this->connection->connectToPersistentSubscriptionAsync(
                        $this->subscription->getStream(),
                        $this->subscription->getGroupName(),
                        $eventAppeared,
                        $this->createSubscriptionDroppedHandler(),
                        $this->bufferSize,
                        false
                    );
 
                    $promise->onResolve(function (?Throwable $exception, ?Subscription $subscription) use ($eventAppeared) {
                        if ($exception) {
                            $this->logger->critical($exception->getMessage());
                        }
 
                        if ($subscription) {
                            $eventAppeared->init($subscription);
                        }
                    });
                });
            });
        });
```

**Comment by prolic** [comment]
@jvdlaar Try this first: Move the  connectToPersistentSubscriptionAsync` out of the `onConnected` method. You don't need that. If you still encounter problem, I hope to find some time this weekend.

**Comment by jvdlaar** [comment]
Well I moved it there to make sure that it reconnects to the persistent subscription after an eventstore reconnect. Without this it'll only reconnect to the event store, but it will not reconnect to the subscription.

**Comment by prolic** [comment]
Please have a look here, as this is the exact same behaviour: https://github.com/EventStore/EventStore/issues/1324#issuecomment-305475324

**Comment by SlayerBirden** [comment]
Hi @prolic I have a question regarding the "restarting subscription in _subscriptionDropped_ handler". `\Prooph\EventStore\Async\PersistentSubscriptionDropped::__invoke` returns "void", so I can't use it as Generator. If I try to call `connection->connectToPersistentSubscriptionAsync(` without yield - it just does nothing, if I try to call it inside a "second" Loop::run - it complains that connection has been closed already.

Sorry, I don't have much experience with async, so it may be a stupid question - but what's the correct way to re-subscribe from PersistentSubscriptionDropped handler?

**Comment by enumag** [comment]
@SlayerBirden I suppose I can share my solution. See https://gist.github.com/enumag/9ee5fe4f527946c6c60efba4b2051491#file-connecttopersistentsubscriptioncommand-php-L179-L226

**Comment by SlayerBirden** [comment]
@enumag thanks so much for sharing your solution, it does work for me and subscription is re-created!
