### ISSUE TITLE
[Help needed] Trying to understand subsciptions

### ISSUE THREAD

**Issue by bogdangrigore** [prooph/event-store-client#88]
I am currently writing a PHP project using GYES as the data storage. 

I am trying to make a simple read model based on users that register in my application. 

In the Event Store I have activated the $by_category projection. I have also created a persistent subscription for the $ce-user stream. 

Starting from [this](https://github.com/prooph/documentation/blob/master/event-store-client/readmodels.md) example provided by you guys, I created a simple script that connects to the subscription and processes the events.

However I am confused. The $ce-user stream contains all the events that have been triggered for streams of the form "user-id". Events with types like "UserCreate" or "UserEmailChanged". However when I run the script the events that I get in my \Prooph\EventStore\Async\EventAppearedOnPersistentSubscription specific implementation are of the type "$>" and contain data like "0@user-483e374c-2008-3965-b59b-c8c11c9d6183" which is obviously a reference to the user stream that was involved in another type of event. 

I assumed that by subscribing to the $ce-user stream I would be receiving the events that were triggered on those specific streams. Can you please help me with what I am doing wrong?

**Comment by prolic** [comment]
Set resolveLinkTos to true

**Comment by bogdangrigore** [comment]
@prolic Thank you very much. That was extremely helpful! I completely missed that option when I created the subscription.
