### ISSUE TITLE
Possible bug when trying to use the ProjectionsManager

### ISSUE THREAD

**Issue by bogdangrigore** [prooph/event-store-client#89]
So I have the following code:
   
`$userCredentials = new UserCredentials('admin', 'changeit');`
`$httpEndpoint = new EndPoint('172.18.0.2', '2133');`
`$projectionManager = new ProjectionsManager($httpEndpoint, 1000);`
`yield $projectionManager->enableAsync('$by_category', $userCredentials);`

The code above results in `Fatal error: Uncaught Amp\Socket\ConnectException: Connection to tcp://172.18.0.2:2133/ refused in /var/www/html/vendor/amphp/artax/lib/DefaultClient.php on line 424`

It seems that although I am trying to use the HTTP API, the client is trying to connect via TCP.

Doing a little debugging I found that you get to \Amp\Artax\HttpSocketPool::checkout wkith the correct URI http://172.18.0.2:2133 but it passes through the next blocks of code where the proxy should be set up. Then it reaches line 77, enters the if because no proxy is detected and attempts to connect via TCP (line 78).

Any idea on how to get this working?

**Comment by enumag** [comment]
To use the HTTP API you need https://github.com/prooph/event-store-http-client instead of this package.

**Comment by bogdangrigore** [comment]
@enumag Well that would explain why it does not seem to be working. Thank you for your answer!

**Comment by prolic** [comment]
@enumag that's a wrong answer

the projections manager works via http api only.

@bogdangrigore have a look at the unit tests, f.e. tests/when_creating_one_time_projection.php

**Comment by enumag** [comment]
Oh. Sorry then.

**Comment by bogdangrigore** [comment]
@prolic As far as I can tell the tests and my implementation are the same as the example in the unit tests. 

    `$userCredentials = new UserCredentials(getenv('EVENTSTORE_USER'), getenv('EVENTSTORE_PASSWORD'));`
    `$httpEndpoint = new EndPoint(getenv('EVENTSTORE_HOST'), getenv('EVENTSTORE_HTTP_PORT'));`
    `$connectionSettings = ConnectionSettings::create();`
   ` $connectionSettings = $connectionSettings
        ->setDefaultUserCredentials($userCredentials)
        ->build();`
    `$endpoint = new EndPoint(getenv('EVENTSTORE_HOST'), getenv('EVENTSTORE_TCP_PORT'));`
   ` $connection = EventStoreConnectionFactory::createFromEndPoint($endpoint, $connectionSettings);`
    `yield $connection->connectAsync();`

   ` $projectionManager = new ProjectionsManager($httpEndpoint, 5000);`
    `yield $projectionManager->enableAsync('$by_category', $userCredentials);`

The ENV values I am using are : 
`EVENTSTORE_HOST="172.18.0.2"`
`EVENTSTORE_TCP_PORT="1113"`
`EVENTSTORE_HTTP_PORT="2133"`
`EVENTSTORE_USER="admin"`
`EVENTSTORE_PASSWORD="changeit"`

If I try from the command line `curl -X POST http://172.18.0.2:2113/projection/$by_category/command/enable -H "Content-Length: 0" -u admin:changeit` I can connect to the server without a problem.

**Comment by bogdangrigore** [comment]
@prolic Never mind. I was using the wrong port in the ENV variables. Sorry.
