### ISSUE TITLE
Best connection methodology on K8S

### ISSUE THREAD

**Issue by MassiAtHG** [prooph/event-store-client#92]
I am struggling finding the best way to connect to an ES running on K8S in a cluster formation of 2. I was not able to connect properly in any way apart from using 'discover' which resulted though in 'HEARTBEAT TIMEOUT at pkgNum ...' errors until the max retry attempts are reached.

**Comment by prolic** [comment]
Clusters need to have odd numbers, like 3, 5, 7, and so on

**Comment by MassiAtHG** [comment]
I set the cluster size to 3 and discovery worked properly. Thanks a lot.

**Comment by prolic** [comment]
you're welcome
