### ISSUE TITLE
Outdated readme

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-client#99]
I wanted to work on a pull request but I need to be able to run the tests. The readme says to use `./run-node.sh --run-projections=all --mem-db` but there is no `run-node.sh` file. Please update the readme accordingly.

**Comment by prolic** [comment]
this is part of the event-store server:

```
cd /home/sasa/Downloads/EventStore-OSS-Linux-Ubuntu-18.04-v5.0.1
ls
```

does it help?

**Comment by enumag** [comment]
Oh... well that's really unclear... Anyway I'm not interested in running the eventstore locally. I want to do it with Docker. Which I eventually found [here](https://github.com/prooph/event-store-client/tree/master/docker/unittest) - that should be linked from the readme too. It doesn't really work after my updates though as mentioned in the PR.

**Comment by prolic** [comment]
You can also use in-memory-db with docker, you have to set it as environment variable.

**Comment by prolic** [comment]
I updated the readme via f0ede57613aeff28b4b83c0fe1879210e9752fe6

**Comment by enumag** [comment]
👍
